
# 400 error will be thrown above this limit.
max_locations_per_request: 200 

# CORS header. Should be null for no CORS, '*' for all domains, or a url with
# protocol, domain, and port ('https://api.example.com/'). Default is null.
access_control_allow_origin: "*"

datasets:
- name: srtm30m
  path: data/srtm30m/
